sudo: false
dist: precise
language: php

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 5.3
  - 5.4
  - 5.5
  - 7.0
  - 7.1
  - hhvm

matrix:
  include:
    - php: 5.6
      env: SYMFONY_VERSION=2.3.x
    - php: 5.6
      env: SYMFONY_VERSION=2.7.x
    - php: 5.6
      env: SYMFONY_VERSION=2.8.x
    - php: 5.6
      env: SYMFONY_VERSION=3.0.x
    - php: 5.6
      env: TWIG_VERSION=2.0.x-dev
    # test the latest release (including beta releases)
    - php: 7.1
      env: DEPENDENCIES=beta      
  fast_finish: true

before_install:
  - if [ "$DEPENDENCIES" = "beta" ]; then composer config minimum-stability beta; fi;
  - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then phpenv config-rm xdebug.ini; fi
  - if [[ "$SYMFONY_VERSION" != "" ]]; then composer require --dev symfony/symfony:$SYMFONY_VERSION; fi
  - if [[ "$TRAVIS_VERSION" != "" ]]; then composer require --dev twig/twig:$TWIG_VERSION; fi

install:
  - composer install --prefer-dist

notifications:
  email:
    - michelsalib@hotmail.com
